// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9rpY5qdE7l7xC62nlOX4nQSBFIIX1QbQ',
    appId: '1:51549478825:web:2b719398d95643f1e96eb8',
    messagingSenderId: '51549478825',
    projectId: 'studymanager-95814',
    authDomain: 'studymanager-95814.firebaseapp.com',
    storageBucket: 'studymanager-95814.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy6k3lKQahvdeRUbbJZh_Okpw2G431Q4k',
    appId: '1:51549478825:android:ebef23ae214d034fe96eb8',
    messagingSenderId: '51549478825',
    projectId: 'studymanager-95814',
    storageBucket: 'studymanager-95814.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGzGf997FZPPxOSovPZBjqdZhUlEqQEEs',
    appId: '1:51549478825:ios:2ee1f1d6ed686645e96eb8',
    messagingSenderId: '51549478825',
    projectId: 'studymanager-95814',
    storageBucket: 'studymanager-95814.firebasestorage.app',
    iosBundleId: 'com.example.studyManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGzGf997FZPPxOSovPZBjqdZhUlEqQEEs',
    appId: '1:51549478825:ios:2ee1f1d6ed686645e96eb8',
    messagingSenderId: '51549478825',
    projectId: 'studymanager-95814',
    storageBucket: 'studymanager-95814.firebasestorage.app',
    iosBundleId: 'com.example.studyManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9rpY5qdE7l7xC62nlOX4nQSBFIIX1QbQ',
    appId: '1:51549478825:web:c4b05f4029e40e83e96eb8',
    messagingSenderId: '51549478825',
    projectId: 'studymanager-95814',
    authDomain: 'studymanager-95814.firebaseapp.com',
    storageBucket: 'studymanager-95814.firebasestorage.app',
  );
}
